config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "friends#index"
  # root "home#index"
  get "home/about"
  get "home/index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, expect: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Autherized!" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twitter, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<!-- <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form> -->






<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, class:"form-control", id: :friend_user_id, value:current_user.id, type: "hidden"%>
  </div>

  <!-- <button type="submit" class="btn btn-primary"> -->
    <%= form.submit class:"btn btn-primary"%>
  <!-- </button> -->
 
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>



<div class="card">
  <div class="card-header">
    <h2>Editing friend</h2>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

<br/>

<div class="d-flex p-2">
  <%= link_to "Show this friend", @friend,  class: "btn btn-secondary btn-sm d-inline p-2" %> 
   <%= button_to 'Delete', @friend, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm d-inline p-2" %>
   <%= link_to "Back to friends", friends_path,  class: "btn btn-secondary btn-sm d-inline p-2" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td>
            <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
          </td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <td><%= button_to 'Delete', friend, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<% else %>

<h1>Hello World!</h1>
This is my first Rails Webpage...

<% end %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<div class="card">
  <div class="card-header">
    <h2>New friend</h2>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>




<br/>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-uppercase"><%= @friend.first_name %> <%=@friend.last_name %></h1>
  <h3 class="display-8"><%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %></h3>

<br/>

  <div class="d-flex">
    <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-secondary btn-sm  d-inline p-2" %> 
    <%= link_to "Back to friends", friends_path, class: "btn btn-sm btn-secondary  d-inline p-2"%>  
    <%= button_to 'Delete', @friend, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm d-inline p-2" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Friends App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
<!--         <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/home/about">About</a>
      </li> -->

      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="/friends">Friends</a>
        </li>
                <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
<!--     <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->

    <ul class="navbar-nav mr-right my-2 my-lg-0">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "tn btn-outline-primary btn-sm" %>
        </li>
      <% else %>
        <li class="nav-item">
             <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-primary btn-sm my-2 my-sm-0" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-primary btn-sm my-2 my-sm-0" %>
          </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>This is about page</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Friends App</title>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>
    <br/>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end %>
      
      <%= yield %>
      
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>